replicaCount: 1

image:
  repository: nginx
  tag: 1.27-alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

route:
  enabled: true
  host: ""
  tls:
    enabled: false
    termination: edge

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
