apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-nginx
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/you/your-repo.git
    targetRevision: main
    path: charts/demo-nginx
    helm:
      releaseName: demo-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
